### ISSUE TITLE
Error: Could not connect to server (public access link)

### ISSUE THREAD

**Issue by roemhildtg** [getodk/central#161]
I installed ODK Central on my local linux distro using the docker install steps. I setup the `.env` file as:

```
SSL_TYPE=selfsign
DOMAIN=lvh.me
SYSADMIN_EMAIL=me@me.com
```

Everything seems to work up until the point where I generate a public URL. Enketo loads, but there's a network error going to:

```
https://lvh.me/-/transform/xform/hwuEO48el0oLrrybRrYWt1yqW9hX0ds?st=mYLJtYV2yuIj6KB6v4HJtJBwhN63UBW3sXaLX!gkl9Fdce%24hRxF4D8xkfCMVzMzD
```

with the response 

```
{code: 500, message: "Could not connect with Server"}
```

I feel like this could be SSL related, can anyone confirm or offer suggestions? Thank you.

**Comment by lognaturel** [comment]
I don't believe that Enketo allows self-signed certificates. There's some related conversation [on the forum](at https://forum.getodk.org/t/enketo-certificate-issue-on-central-0-9/28578/12). What happens if you try to load a preview (which also uses Enketo)?

I know we have some language recommending issues get filed here but we should modify that! In general, first going to the forum gets more of the community involved. Then if there does turn out to be a code change needed, the devs can triage and file as needed.

**Comment by roemhildtg** [comment]
Thanks @lognaturel  - I will visit the forum in the future for stuff like this. I'll review your question and get back to you tomorrow hopefully, but I'm fairly certain I ran into the same issue with preview, and you are correct - in that the preview also does not work.

**Comment by roemhildtg** [comment]
Just confirming - the preview does not work. I will close this as it is an enketo issue related to self signed certs.
