### ISSUE TITLE
Different options for Backup

### ISSUE THREAD

**Issue by andybennett85** [getodk/central#167]
Just wondering if it was planned for future releases, or I could make the suggestion, that different options other than Google Drive be made available for backups.

For instance, would a backup to a local storage drive, or networked drive be available without having to access the backend of Central?

In cases where Clinical or identifiable data is collected, I'm not 100% convinced of Google Drive's compliance with data protections laws - which might well be a personal choice/opinion, but it would be good if Central offered other options and not just Google Drive.

**Comment by issa-tseng** [comment]
if it helps at all, the data is entirely encrypted before being sent to google. it cannot be decrypted in any way without your passphrase.

a networked drive may be a possible target much further down the road, or with a PR (which would have to include a PR against the frontend admin panel as well). local storage is less likely due to the way Docker works.

**Comment by matthew-white** [comment]
Hi @andybennett85! We have released ODK Central v1.1, which allows you to immediately download a backup of your database to your own computer. As of v1.1, you will need to have Google Drive backups configured in order to access this functionality in the web management interface. However, you can also use the API to download a backup without configuring Google Drive backups.
