### ISSUE TITLE
Certbot rate limit hit 

### ISSUE THREAD

**Issue by parthibd** [getodk/central#175]
Every time I do a `docker-composer down` followed by a `docker-compose up` , a new certificate is issued, after repeating this a few times , letsencrypt's rate limit is hit . Is there a way to avoid creating new certificated with restart ?

**Comment by lognaturel** [comment]
Sorry you are running into this. The recommended approach for Central management is to never use `docker-compose down` and instead always use `stop`. That is what we have documented.

Could you tell us more about why you regularly do `docker-compose down`?

**Comment by parthibd** [comment]
I was testing ODK central against both `stop` and `down` . But I came across this problem when I was trying to make some custom changes to the frontend and backend and had to allow these changes to be reflected in the containers . I believe I am wrong in my approach to use `docker-compose down` .

**Comment by lognaturel** [comment]
Are you doing active development or applying patches you've already developed and want to push to production? I believe that a `stop` is sufficient even for active development but in general, we don't recommend using the Docker setup for that. See https://github.com/getodk/central-frontend#running-in-development and https://github.com/getodk/central-backend#setting-up-a-development-environment for setting up a development environment.

**Comment by parthibd** [comment]
I am trying to do active development . I have gone through how to setup the `frontend` and `backend` for development . But I was lost while trying to setup `enketo` and other direct dependencies  of `central` . There is no documentation on how to install central on a bare metal server .

**Comment by lognaturel** [comment]
The instructions I linked you to should get you started. Did you try those? I can write up some instructions for Enketo likely tomorrow.

> other direct dependencies of central
Could you please elaborate? You shouldn't need pyxform-http for development. What else are you looking for?

**Comment by parthibd** [comment]
I'm actually trying hack around enketo to implement edit form submission functionality. But I need enketo to work at least. Can you please guide me?

**Comment by lognaturel** [comment]
I'm realizing now that although we can get Enketo working for draft links and public links locally relatively easily, submission links and eventually edit links will require cookie auth. This means requests must be over https and so it's not practical to do in a local dev environment.

I think your best bet will be to drive your local development from tests and then when you have a full solution you can pull your commits in a production environment and rebuild after a `docker-compose stop` rather than a `down`.

I now see that we've already had some discussion. Please make sure you've read my post at https://forum.getodk.org/t/ability-to-edit-and-delete-submission-data/31026/9! Taking on a smaller issue would be a great place to start if you'd like to eventually contribute something larger to the codebase.
