### ISSUE TITLE
OData API: Metadata Document not available

### ISSUE THREAD

**Issue by mattelacchiato** [getodk/central#197]
I'm trying to `GET` the metadata document as described here: https://odkcentral.docs.apiary.io/#reference/odata-endpoints/odata-form-service/metadata-document

I receive a valid response for 
```/v1/projects/1/forms/[form_id].svc```
as well as for 
```/v1/projects/1/forms/[form_id].svc/Submissions```
but not for 
```/v1/projects/1/forms/[form_id].svc/$metadata```

The last call responds with 404:
```json
{
  "message": "Could not find the resource you were looking for.",
  "code": 404.1
}
```

```
versions:
542b21b1441dd64bddde90915aafc2e0b4aa54b2
 93e4b5b80acd8941d8ebf6d82a116d7db7515289 client (v1.1.0)
 a33bc6fb3c34fe38894b0e9d0bb404f81da325e6 server (v1.1.1)
```

**Comment by matthew-white** [comment]
Hi @mattelacchiato! What tool are you using to send the request? I'm wondering whether it would help to encode `$` by replacing it with `%24`.

For future issues, I also recommend going to the ODK forum, as that gets more of the community involved. Then if there turns out to be a code change needed, the devs can triage and file issues as needed.

**Comment by mattelacchiato** [comment]
Oh, you're right, it was a client issue! I was using Insomnia, but `curl` now shows me that it's working correctly. Sorry...
