### ISSUE TITLE
Service Announcements

### ISSUE THREAD

**Issue by andybennett85** [getodk/central#202]
Would like to see a function that allows for Service Announcements to be sent to Project Managers or Admins within ODK Central. Perhaps downtime is planned for upgrading of server or base OS, rather than having a separate log of Project Managers who you then need to contact, you could have an option to announce this via Central using the email service.

**Comment by matthew-white** [comment]
Hi @andybennett85! We  had a different but related discussion about downtime on the forum [here](https://forum.getodk.org/t/zero-downtime-deployment-high-availability-cluster/32418). @lognaturel wrote there:

> We typically see around a second of downtime when doing updates and schedule them when we see the least traffic in a typical week.

I think an announcement feature would involve some complexity, since there could be different preferences across servers about which groups receive which announcements. If possible, I think the best bet might be to minimize downtime and the need for service announcements.

**Comment by matthew-white** [comment]
I'm going to go ahead and close this issue for now so that we can keep things organized on GitHub. If you have additional thoughts about this feature, we'd love to hear about them on the ODK Forum. (I saw that you recently joined the Forum. 😄) In general, the Forum is the best place to start most conversations, as more of the community is active there.
