### ISSUE TITLE
Double-check Postgres + Node on July 1

### ISSUE THREAD

**Issue by matthew-white** [getodk/central#282]
Central uses Postgres 9.6 along with an image for Node 14. @yanokwa investigated how long this combination will be supported. Notes from that investigation are copied below, but in summary, it seems that no action is needed. However, we will double-check around July 1, when the Node image will change.

<hr>

From Slack (Jan 27):

> For the server, we are running it in a container. It looks like Docker removes old versions from their repo (e.g., PostgreSQL 9.5 was removed in May https://github.com/docker-library/postgres/commit/56eb8091dc67efe65b7a5a101e80ab83a9ca70a3) but they seem to leave the container images themselves on Docker Hub. In fact, I can go as far as back as PostgreSQL 8.4 (~2014) in my docker-compose.yml and that builds and runs, so we are fine there.
>
> For the client, we install psql from PostgreSQL’s deb site (https://apt.postgresql.org/pub/repos/apt/dists/) on the service container. The container is currently Node 14 running on Debian 9 Stretch which will be deprecated in June 2022. PostgreSQL doesn’t have any old OSes on their deb site, so I would expect that we will not be able to run install on Stretch after June.
>
> But node seems to have pretty much all the various node and Debian combinations available on Docker Hub (https://hub.docker.com/_/node) so we should be able to upgrade the service container to Debian 10 Buster and stay with Node 14 or upgrade to Node 16. And as long as we are on Buster, we can install psql versions back to 8.2.
>
> As far as an action item, maybe we change service.dockerfile to use node:14.17.6-buster so we are sure we are on Buster and not Stretch and ship an update before June.

<hr>

Mar 14

> I wonder if the node people will automatically switch from stretch to buster when stretch reaches EOL in June. https://github.com/nodejs/docker-node/pull/1288 suggests that it will. So I guess the question is do we want to explicitly bind to a particular OS version. My bias is no.
>
> &hellip;
>
> I don’t think [users] need to rebuild. But if they do, they’ll get the new OS.

<hr>

As close to July 1 as possible, we should verify that this is working as expected. We could consider checking both new and existing servers.

**Comment by matthew-white** [comment]
Tomorrow is July 1! @yanokwa, since you were investigating these questions, are you able to double-check these things?

**Comment by yanokwa** [comment]
As of July 5th, new installs of Central use Debian 9 (Stretch) for the service container (node:14.17.6). I confirmed this by logging into the container and running `cat /etc/debian_version`. 

But node has [dropped Stretch](https://github.com/nodejs/docker-node/commit/4f1d6a3875d1833ef57d87ed1999c41dbe6bd82c) from their repo because it is EOL.

The most conservative (and thus likely safest) thing to do is to upgrade the service and nginx dockerfiles to go from `node:14.17.6` to `node:14.19.3-buster` (EOL: June 2024). We could also do `node:14.19.3-bullseye` (EOL: June 2026).

Node 14 is EOL on April 2023, so we could also look to upgrading to Node 16 (EOL: Sept 2023) or Node 18 (EOL: April 2025).

As far as a strategy or policy, my bias is we get on the most recent LTS on all containers. And we confirm we are the first thing after a release stabilizes (similar to what we do on Collect).

**Comment by matthew-white** [comment]
@yanokwa, do you think this issue is ready to be closed?
