### ISSUE TITLE
Show Datasets on homepage

### ISSUE THREAD

**Issue by matthew-white** [getodk/central#460]
See the story in the [release criteria](https://docs.google.com/document/d/1lEIp5te0-SkA9xEPwqQdf3Kp6ciTqY8UxGBosoKPK5Q/edit#heading=h.b0aclwe4ye91).

**Comment by matthew-white** [comment]
I think this is done, but @sadiqkhoja, but reopen if not!

**Comment by sadiqkhoja** [comment]
@getodk/testers this can be tested on staging environment

**Comment by dbemke** [comment]
What is the default number of forms and datasets shown on the homepage?
When I'm logged in on staging as an administrator I can see 3 forms and 3 dataset.
If I log in as role None the number of shown datasets and forms is different.

Administrator:


![Image](https://github.com/getodk/central/assets/56479916/9fe54243-bfcd-46a4-a619-0aa33abc1db5)

Role - None:


![Image](https://github.com/getodk/central/assets/56479916/26f94c04-86b2-4bd4-9b53-91859a807df5)

**Comment by dbemke** [comment]
Is the appearance of the show/ hide option somehow connected with the number of projects on the home page (e.g. if there's only 1 project there isn't show/hide list)?

The screenshot shows a user (not administrator) with access to only 1 project ( 9 forms on the list, no option to show/hide forms):



![Image](https://github.com/getodk/central/assets/56479916/e5dff3aa-be8a-476c-a664-31760dd62634)

**Comment by sadiqkhoja** [comment]
It's complicated logic based on number of projects, Forms and Entity Lists (aka Datasets).

Fundamentally, we try to show "**around**" 15 Forms and 15 Entity Lists (aka Datasets), so if there are less 15 across the all the projects then all are shown otherwise we hide.

Here are some examples of the behaviour:

- 4 Projects, each have 10 Forms then 3 are shown (if we show 4 of each then total shown would be 16 - we don't want that)
- 2 Projects, each have 10 Forms then 7 are shown (14 in total)
- 3 Projects, each have 10 Forms then 5 are shown (15 in total)
- 1 Project having 14 Forms and 1 Project has 1 Form then all 15 Forms are shown
- 15 Projects having only 1 Form then all 15 Forms are shown

**Comment by dbemke** [comment]
**Tested with success!**

**Comment by srujner** [comment]
Tested with success!
