### ISSUE TITLE
Form creating entity without properties isn't visible in Dataset overview - connections to forms

### ISSUE THREAD

**Issue by dbemke** [getodk/central#464]
#### Problem description
If a form creates entities but doesn’t include any properties of the entity, in the Dataset overview on Central there is "0 forms creates Entities in this Dataset”.
#### URL of the page
https://staging.getodk.cloud/#/projects/20/datasets/directors
#### Steps to reproduce the problem
1. Upload and publish a form creating entities without anything in the saveto field (e.g. director entities form version 1 in https://staging.getodk.cloud/#/projects/20/forms/director%20entities). 
2. Go to the dataset overview.
#### Screenshot
![zeroconnections](https://github.com/getodk/central/assets/56479916/f8b3fb5e-f7a9-4a21-af7d-e731a1d3a9e6)

#### Expected behavior
All connections to forms creating entities should be present in the Dataset overview.
#### Central version shown in version.txt
https://test.getodk.cloud/ 
versions:
906addf66af230735e501ad73a1269012fdd7a5a (v2023.3.1)
+330132cf1ecb824b1fb88894287cb8edb5acefa5 client (v2023.3.0-2-g330132cf)
 ba6ee474f431b48e885fb035c9266792f06d0ad7 server (v2023.3.1)
https://staging.getodk.cloud/
versions:
f78da7a8b7a132ad2baa794a656da6ba8e40754a (v2023.3.1-6-gf78da7a)+7857fc455985f19e58e5e9a2108137ecd59419bb client (v2023.3.0-12-g7857fc45)+83e453326c9aeded6297c1ef5af63aa0efc782b4 server (v2023.3.1-29-g83e45332)
#### Browser version
Chrome 114.0.5735.198, Firefox 116.0.2

**Comment by matthew-white** [comment]
Just to check, is this an existing bug in v2023.3? Or is it a .4 regression? (Is this behavior visible on sandbox.getodk.cloud?)

**Comment by dbemke** [comment]
I reproduced it in versions mentioned in "Central version shown in version.txt". On both there are 2023.3. versions. Should there be 2023.4 on one of them? 
On sandbox.getodk.cloud I think I'm not an administrator so I can't create projects ( I can just view projects).

**Comment by matthew-white** [comment]
Oh sorry, you and Szymon should both be administrators on that server! I've updated your roles.

> I reproduced it in versions mentioned in "Central version shown in version.txt". On both there are 2023.3. versions. Should there be 2023.4 on one of them?

2023.4 won't be visible in any version.txt until after 2023.4 is released. You can see how similar a server is to a released version by looking at the number surrounded by hyphens after the version number. Examples:

version.txt on sandbox.getodk.cloud

- `server (v2023.3.1)`. This means that the server/backend/API exactly matches v2023.3.1.
- `client (v2023.3.0)`. This means that the client/frontend/UI exactly matches v2023.3.0. (There weren't any changes to the UI between v2023.3.0 and v2023.3.1, which is why it says v2023.3.0 and not v2023.3.1.)

version.txt on test.getodk.cloud

- `client (v2023.3.0-2-g330132cf)`. The `-2-` means that there have been 2 changes to the UI relative to v2023.3.0. (I made an experimental change there while working on #451, which I should probably roll back.)

version.txt on staging.getodk.cloud

- `server (v2023.3.1-32-g841f215f)`. There have been 32 changes to the API relative to v2023.3.1.
- `client (v2023.3.0-13-gad92f114)`. 13 changes to the UI.

If you reproduced this on test.getodk.cloud, which is very close to the current stable behavior, then it sounds like this is an existing bug.

**Comment by sadiqkhoja** [comment]
@getodk/testers this can be tested on staging environment

**Comment by dbemke** [comment]
**Tested with success!**

**Comment by srujner** [comment]
Tested with success!
