### ISSUE TITLE
"Invalid Dataset property" error message to be updated?

### ISSUE THREAD

**Issue by dbemke** [getodk/central#487]
#### Problem description
I’m not sure if after the latest changes this it the expected error message ("Invalid Dataset property”).

#### Steps to reproduce the problem
1. Upload the form with the invalid field.
[trees_registration_propertnameisname(1).xml.txt](https://github.com/getodk/central/files/12661368/trees_registration_propertnameisname.1.xml.txt)

#### Screenshot

![errorDataset](https://github.com/getodk/central/assets/56479916/bd0f639b-4d60-4b00-a2e9-a4565cc1b568)

**Comment by matthew-white** [comment]
I think you're right that "Dataset" shouldn't be shown to users in error messages. Linking to the related comment [here](https://github.com/getodk/central/issues/466#issuecomment-1721620094).

**Comment by ktuite** [comment]
I wrote more about this in the PR https://github.com/getodk/central-backend/pull/999 but I ended up making very small changes to the error messages in the backend only.

- There are many different "reasons" form parsing for an entity form can fail, and it doesn't make sense to translate them all on the frontend. 
- Some of the reasons ought to mention "datasets" specifically, because at that point in the process, the XML does contain the word "dataset". Most users are unlikely to see this case, though, if they work in a spreadsheet, because pyxform will do its own checking and validation and return friendlier errors.
