### ISSUE TITLE
See update conflicts in Entity table

### ISSUE THREAD

**Issue by matthew-white** [getodk/central#504]
See the story in the [release criteria](https://docs.google.com/document/d/1EdEDcXoJmrryFYNc56zciuQ82G_iVGBQf1UFEkWiUtw/edit#heading=h.ntgf4dkssnwf).

---

Related:

- #511
- getodk/central-backend#1024
- getodk/central-backend#1023
- getodk/central-backend#1037
- getodk/central-backend#1028
- getodk/central-frontend#882
- getodk/central-frontend#883
- getodk/central-frontend#884
- #529

**Comment by matthew-white** [comment]
I'm going to move this back to "in progress", since I still need to add the conflict summary table to the modal (#529). I'll assign myself to the issue. Once the table is done, I think this story will be ready for QA and design review.

**Comment by issa-tseng** [comment]
there's awkwardly much distance between the alert icon and the >
if i take 8px out of the distance it looks nicer but it seems like it should be aligned or floated right instead of the width being changed as i did it

as i think sadiq expressed, the alert icon is pretty big. if i take the icon font size down to 12px, the circle to 22px, and realign the icon it looks nicer

as szymon notes, titlebar is still magenta. i can live with it

at least in safari i see the first header column is collapsed, that column we should see at least the full static contents.
![Image](https://github.com/getodk/central/assets/117762/093f8486-fb4b-4aea-a9de-9b922f8aa6d7)

have not personally tested project viewer but looks good otherwise

**Comment by srujner** [comment]
**Tested with Success!**

**Comment by dbemke** [comment]
Tested with Success!

**Comment by matthew-white** [comment]
> there's awkwardly much distance between the alert icon and the > if i take 8px out of the distance it looks nicer but it seems like it should be aligned or floated right instead of the width being changed as i did it
> 
> as i think sadiq expressed, the alert icon is pretty big. if i take the icon font size down to 12px, the circle to 22px, and realign the icon it looks nicer

I've made these changes as part of getodk/central-frontend#903. I similarly adjusted the alert icon in the table of entity lists.

> at least in safari i see the first header column is collapsed, that column we should see at least the full static contents.

I left a related [comment](https://docs.google.com/document/d/1EdEDcXoJmrryFYNc56zciuQ82G_iVGBQf1UFEkWiUtw/edit?disco=AAABBPvYUSo) about these column widths in the release criteria.

> have not personally tested project viewer but looks good otherwise

I don't think this was in place when you took a look, but it should be now that #538 is closed.
