### ISSUE TITLE
Entity error not shown for nonexistent base version

### ISSUE THREAD

**Issue by matthew-white** [getodk/central#536]
#### Problem description

I created a form on staging that allows you to specify the entity `baseVersion` attribute. At one point, I had an error in my form logic that caused `baseVersion` to be set to 2 when there was only one version (when `baseVersion` had to be 1). I created a submission using this version of the form, but I saw neither an entity update nor an entity error in the submission feed:

https://staging.getodk.cloud/#/projects/49/forms/trees_update2/submissions/uuid%3A0e6ca580-3bd0-449c-a082-4b9c74778d3b

I'm pretty sure this is an issue in Frontend. I see an `entity.error` event returned by Backend, but it's not shown in the feed. I see the following error in the browser console:

```
TypeError: Cannot use 'in' operator to search for 'problemDetails' in null
    at Proxy.entityProblem (feed-entry.vue:182:9)
    at feed-entry.vue:73:62
```

#### Expected behavior

If I specify a base version that doesn't exist, I expect to see some error.

#### Central version shown in version.txt

```
versions:
774b491961578bd6e03ceaa6cf8032dd27b828a7 (v2023.4.0-2-g774b491)
+093a238344680720532333a9c4200aa3ef3266c8 client (v2023.4.0-9-g093a2383)
+9d1bbd73e04b428f0ac7c474acbc94e39c1ad818 server (v2023.4.0-25-g9d1bbd73)
```

**Comment by ktuite** [comment]
Just looked into this more. 

There's a step where backend tries to look up the base version of an entity, and that can throw a `NotFoundError: Resource not found.` which is an _error_ rather than a _Problem_.

```
{
  "problem": null,
  "errorMessage": "Resource not found.",
  "submissionId": 582,
  "submissionDefId": 604,
  "entity": {}
}
```

I guess frontend should be able to show errors like that, where we didn't even catch the right thing... where `problem` is `null` and there is an `errorMessage`. 

However, for this specific case, I'm going to have it return a problem with a more specific message about not finding the entity with the right base version.
