### ISSUE TITLE
After updating an entity the number in the "Download x Entities” button for a moment shows a higher number (+1) 

### ISSUE THREAD

**Issue by dbemke** [getodk/central#560]
#### Problem description
After updating an entity the number in the "Download x Entities” button for a moment shows a higher number (+1) than the number of entities in the entities table (the Data tab).
After following the steps below, if I refresh the page again (sometimes more than once) the number will get corrected. When the number is wrong in the downloaded CSV there isn't an extra record.
Some time after filing the issue I reopened the link below and I can see that the number is again +1 although it got corrected after refreshing.
#### URL of the page
used forms and dataset in
https://staging.getodk.cloud/#/projects/62/entity-lists/trees/entities
#### Steps to reproduce the problem
(Preconditions: Trees registration and Trees update form are added in Collect)
1. Submit a new entity in Trees registration form via Collect.
2. Go to Entity Data tab on Central and refresh the table if necessary (don’t close the tab).
3. In Collect in "Start new form" refresh the list of forms to download the newest entity.
4. Go to Trees update form and update the new entity and send the form.
5. Go back to Central to the Data tab refresh the table and refresh the page.
6. Check the number on the button "Download x entities”
#### Screenshot
![AfterRefresh](https://github.com/getodk/central/assets/56479916/6023ee01-4f84-48d0-922e-b995070fe66b)
![downloadEntities](https://github.com/getodk/central/assets/56479916/200906b4-6397-4011-a89f-42df77d7e0e5)

#### Expected behavior
The number of entities on the list should be equal to the number of entities to download.
#### Central version shown in version.txt
staging versions:
versions:
d2345d0713339b45045167bcf14e24dcf473bdf5 (v2023.4.0-5-gd2345d0)
+4b5d237c5d83f7fc5c64dce79229f9edd97cff62 client (v2023.4.0-46-g4b5d237c)
+c2580569befe146837d770185e49b61ebab5d06e server (v2023.4.0-44-gc2580569)

**Comment by matthew-white** [comment]
I can see at least two issues on this page:

- The extended metadata for the entity list isn't correct. The `entities` property is 9 instead of 8.
- (Less critical, but still unexpected:) When the `entities` property differs from the OData count, Frontend is supposed to use the OData count, which is more likely to be up-to-date. It does that by [patching](https://github.com/getodk/central-frontend/blob/4b5d237c5d83f7fc5c64dce79229f9edd97cff62/src/components/entity/list.vue#L102) `dataset.entities` with the OData count. However, that doesn't seem to be happening here.

**Comment by matthew-white** [comment]
I think this issue is now resolved. When I visit the URL and refresh the page several times, I always see that the count in the button matches the number of rows of the table.

I think the issue had to do with deleted entities: deleted entities were not included in OData or the CSV download, but they *were* included in the count shown in the button.

> After following the steps below, if I refresh the page again (sometimes more than once) the number will get corrected.

I think (but am not 100% sure) that this intermittency had to with the order of responses from the server. If the UI received the entity list object before the OData, then I think it would show the incorrect count in the button. However, if it received the OData before the entity list object, then it would show the correct count.

> After updating an entity the number in the "Download x Entities” button for a moment shows a higher number (+1) than the number of entities in the entities table (the Data tab).

Does that mean that the count in the button sometimes changed even without refreshing the page? Or did it only change when you refreshed the page?

I think the count in the button should now be correct and consistent with the number of rows of the table. If you create or delete an entity, then click the refresh button, the count in the button should change to match the updated number of entities. You should never have to refresh the page to make the two counts match. Let me know if you see any issues related to these counts!

**Comment by dbemke** [comment]
(Before the fix) At first when I used the refresh button the count in the button didn't change, if I refreshed the page the count in the button was wrong. Afterwards refreshing the page changed the number in button to: ok number and +1 number so it was like back and forth changing the number.

**Comment by srujner** [comment]
Tested with Success!

**Comment by dbemke** [comment]
Tested with Success!
