### ISSUE TITLE
While creating a dataset manually via "+New” button, at the end of the error informing that the dataset already exists there is "56” added

### ISSUE THREAD

**Issue by dbemke** [getodk/central#625]
#### Problem description
While creating a dataset manually via "+New” button, at the end of the error informing that the dataset already exists there is "56” added.
#### URL of the page
https://staging.getodk.cloud/
#### Steps to reproduce the problem
1. Navigate to Entities Lists page.
2. Click "+New” button.
3. Enter a dataset name that already exists in the project.
4. Click "Create”.
#### Screenshot

![56inError](https://github.com/getodk/central/assets/56479916/abad4743-f99e-4f84-99c0-d14bf8793f9c)

#### Expected behavior
"56" shouldn't be in the error message.
#### Central version shown in version.txt
https://staging.getodk.cloud/
versions:
f0b2a90bce34fc13b0df4affd8b3158d57bcf904 (v2023.5.1-5-gf0b2a90)
+2bb17a501416814bbd987ddc953abc5b0c40c58a client (v2023.5.0-43-g2bb17a50)
+267e0ad7806057fc82894f58bea680627f1de5cd server (v2023.5.0-49-g267e0ad7)

#### Browser version
Chrome and Firefox

**Comment by lognaturel** [comment]
This is a side effect of error messages being pretty raw! Entity list names are unique within a project. The error message is saying that there is already an entity list with name `trees` in project with id `56`. I agree that it looks strange. It happens across other resources as well and we could consider those together at a later time.

**Comment by matthew-white** [comment]
> It happens across other resources as well

Now that we've resolved #144, I think we've mostly addressed this for other resources. We tend to handle 409 errors on a case-by-case basis rather than in a global way. For example:

- https://github.com/getodk/central-frontend/blob/2bb17a501416814bbd987ddc953abc5b0c40c58a/src/components/user/new.vue#L115
- https://github.com/getodk/central-frontend/blob/2bb17a501416814bbd987ddc953abc5b0c40c58a/src/components/form/new.vue#L314
- https://github.com/getodk/central-frontend/blob/2bb17a501416814bbd987ddc953abc5b0c40c58a/src/components/form-draft/publish.vue#261

I think we could fix this one now or in a future release. We have an existing mechanism to handle Problem responses like this, so it shouldn't be a heavy lift.

**Comment by srujner** [comment]
**Tested with Success**

**Comment by dbemke** [comment]
**Tested with Success**
