### ISSUE TITLE
Names of datasets are case-sensitive

### ISSUE THREAD

**Issue by dbemke** [getodk/central#627]
#### Problem description
Names of datasets are case-sensitive. It's possible to create a dataset e.g. "abc" and "Abc".

#### Steps to reproduce the problem
1. Go to Entity Lists page.
2. Click "+New”.
3. Enter "abc” and click "Create”.
4. Click "+New”.
5. Enter "Abc” and click "Create”.
#### Screenshot

![SameDatasetCapital](https://github.com/getodk/central/assets/56479916/cdc50c0a-2c71-447d-a9d1-f8ef881a06b9)

#### Expected behavior
Names of datasets should be case-insensitive.
#### Central version shown in version.txt
https://staging.getodk.cloud/#/
versions:
f0b2a90bce34fc13b0df4affd8b3158d57bcf904 (v2023.5.1-5-gf0b2a90)
+2bb17a501416814bbd987ddc953abc5b0c40c58a client (v2023.5.0-43-g2bb17a50)
+267e0ad7806057fc82894f58bea680627f1de5cd server (v2023.5.0-49-g267e0ad7)

**Comment by matthew-white** [comment]
@lognaturel, do you think we should slot this issue for .1? I think the issue has probably existed for a little while.

**Comment by matthew-white** [comment]
I just checked, and it does look like it's possible to create two datasets like this by publishing forms: https://staging.getodk.cloud/#/projects/84. We'd like to address that as part of this issue as well: there should be no way to create two datasets like this.

**Comment by ktuite** [comment]
When entities just came from forms, it was okay if form A wrote to dataset "trees" and then form B also wrote to dataset "trees". We didn't check for dataset name collisions and this (combined with not altering the casing of the name) is what is leading to it being possible to create both "trees" and "TREES" as separate datasets. 

Just writing out what I think we want instead:
- whichever case is created first is the true case, e.g. if "TREES" is created first, that is what any other form must use, vs. "trees".
- there should be an error on _form upload_ if you try to upload a form draft that defines a dataset with the same name but different case than already exists (and is published), and it tells you to change the casing to match what exists.
- there should be an error on form publish if you make two drafts with different casing, publish the first, and then try to publish the second.

- should be straightforward to prevent via API

**Comment by ktuite** [comment]
Hi @getodk/testers, 

I wrote in the PR that some of the places you should expect to see errors now include:
* Error on Form Upload if dataset name (e.g. "TREES") conflicts with a published dataset ("trees")
* Error on Form Publish if publishing will introduce a conflict, which can happen if there were multiple draft forms with different name variations ("TREES" and "trees"), one was published ("trees"), and then a second is attempted to be published ("TREES").
* Error on "New Entity List" / API if dataset name conflicts with a published dataset
    * Now allowed to create/publish a dataset that directly collides with an unpublished dataset

Some things you are allowed to do:
* Upload unpublished forms with different capitalization variations of the same dataset. The first one to be published is the one that is locked in.
* Create a form that makes a draft dataset like "trees", and then use the "New Entity List" button to create/publish "trees". Then publishing the form wont publish the dataset because it will already have been published.
    * Similarly, you could probably make two draft forms "trees" and "TREES" and then use the New Entity List button to make a dataset with the name "TrEes", an then block the publishing of both forms.

I have a lot of different tests for different situations, but please play around and see if you find any other weird edge cases!

**Comment by srujner** [comment]
Tested with success!
