### ISSUE TITLE
Missing tooltip in submissions table in geopoints

### ISSUE THREAD

**Issue by dbemke** [getodk/central#635]
#### Problem description
In submissions table when you hover over geopoints submission data (e.g. All widgets form) the tooltip isn’t displayed. It’s impossible to read the whole data in geopoints.

#### Steps to reproduce the problem
1. Send a submission of All widgets form with all Geo question types filled.
2. Go to Central to submissions page.
3. Hover over geopoint data in the submission table.
#### Screenshot
https://jam.dev/c/9f3f9ea7-84e1-4268-939d-2c00ddff37e9

#### Expected behavior
When you hover over data that is longer than the column width, the tooltip should appear
#### Central version shown in version.txt
https://staging.getodk.cloud/
versions:
f0b2a90bce34fc13b0df4affd8b3158d57bcf904 (v2023.5.1-5-gf0b2a90)
+e216a1176b196b2b168ce2d0164eb657061653e0 client (v2023.5.0-45-ge216a117)
+59e2165c01534d651385342d14d8789955320bcd server (v2023.5.0-51-g59e2165c)
https://test.getodk.cloud/
versions:
f0b2a90bce34fc13b0df4affd8b3158d57bcf904 (v2023.5.1-5-gf0b2a90)
+177ab0713f98f2f0f8e46b194b0840e660014c89 client (v2023.5.0-71-g177ab071)
+59e2165c01534d651385342d14d8789955320bcd server (v2023.5.0-51-g59e2165c)

#### Browser 
Chrome and Firefox

**Comment by matthew-white** [comment]
The lack of a tooltip is actually [by design](https://github.com/getodk/central-frontend/blob/e216a1176b196b2b168ce2d0164eb657061653e0/src/components/submission/data-row.vue#L58). The thought is that geopoint values shouldn't ever end up being truncated, so we should enhance performance by skipping the tooltip. Most columns max out at 250px, but geopoint columns are [allowed to grow](https://github.com/getodk/central-frontend/blob/e216a1176b196b2b168ce2d0164eb657061653e0/src/components/submission/data-row.vue#L181) up to 500px. Or at least they're supposed to be. In practice, I can see that that's not happening: they're 250px instead of 500px. I think this is an issue introduced by getodk/central-frontend#811 in v2023.3. The CSS for the default 250px has become more specific, so the CSS for the geopoint 500px is never applied. We should be able to fix this pretty easily.

**Comment by dbemke** [comment]
Tested with success!

**Comment by srujner** [comment]
**Tested with success!**
