### ISSUE TITLE
Testing QR code flyout without option to close it

### ISSUE THREAD

**Issue by dbemke** [getodk/central#847]
#### Problem description
After clicking "Test on device" the see the testing QR code there isn't a way to close the flyout
#### Steps to reproduce the problem
1. Create a draft version of a form.
2. Click "Test on device".
#### Screenshot
![closeTesring](https://github.com/user-attachments/assets/3361d5d3-70d6-43d1-89b9-1acf45a357a9)

#### Expected behavior
Should there be "X" to close the flyout?
#### Central version shown in version.txt

https://staging.getodk.cloud/
versions:
20878c7ffe3b92a2b9f35bb253e6043e5ddba67b (v2024.2.1-11-g20878c7)
+e82c391fbc00f761d9915fe49034eeec1916d87a client (v2024.2.1-70-ge82c391f)
+8837aa5ed78666d31794f8404625fb5a51e41e94 server (v2024.2.0-120-g8837aa5e)
https://test.getodk.cloud/
versions:
20878c7ffe3b92a2b9f35bb253e6043e5ddba67b (v2024.2.1-11-g20878c7)
+e82c391fbc00f761d9915fe49034eeec1916d87a client (v2024.2.1-70-ge82c391f)
+8837aa5ed78666d31794f8404625fb5a51e41e94 server (v2024.2.0-120-g8837aa5e)

**Comment by matthew-white** [comment]
You can close the flyout by clicking outside it or by re-clicking the button/link that showed it in the first place. But if you found it confusing, I bet others will as well. I don't think there's space for an X at the top-right of the flyover (as there is with modals), since the phone icon is there. But here are two alternatives that we could consider:

- Add a close button to the bottom of the flyover.
- Hide the flyover when the Escape key is pressed.

**Comment by dbemke** [comment]
The QR codes overlays a bit the gray bottom part. Would it be possible to move the gray part a bit lower so that it's under the QR code? 
![Image](https://github.com/user-attachments/assets/33bdcfc5-797e-4d30-8bc5-206d9781400f)

**Comment by WKobus** [comment]
**Tested with success!**
